# Containers tasks.
startup-client-container:
	docker-compose up --build -d client

startup-server-container:
	docker-compose up --build -d server

startup-postgresdb-container:
	docker-compose up --build -d postgresdb

shutdown-client-container:
	docker-compose down -v client

shutdown-server-container:
	docker-compose down -v server

shutdown-postgresdb-container:
	docker-compose down -v postgresdb
