# Containers tasks.
startup-client-container:
	docker-compose up --build -d client

startup-server-container:
	docker-compose up --build -d server

startup-mongodb-container:
	docker-compose up --build -d mongodb

shutdown-client-container:
	docker-compose down -v client

shutdown-server-container:
	docker-compose down -v server

shutdown-mongodb-container:
	docker-compose down -v mongodb