services:
  streamlit_app:
    container_name: streamlit-app-container
    build:
      context: .
    env_file:
      - ./.env
    restart: always
    ports:
      - 8501:8501
    depends_on:
      - postgresql
    volumes:
      - streamlit_app_data:/var/lib/streamlit_app/data

  postgresql:
    container_name: postgresql-container
    image: postgres:latest
    environment:
      - POSTGRES_DB=langchain_chat_history_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data

volumes:
  streamlit_app_data:
  postgresql_data:
