[project]
name = "challenge-2025-06-18"
version = "0.1.0"
description = "CSV Analysis Challenge"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "crewai>=0.121.1",
    "langchain-google-genai>=2.1.5",
    "python-dotenv>=1.1.0",
    "streamlit>=1.45.1",
]
