# Containers tasks.
startup-app-container:
	docker-compose up --build -d app

startup-mongodb-container:
	docker-compose up --build -d mongodb






shutdown-app-container:
	docker-compose down -v app

remove-app-image:
	docker rmi desafio-final-app

startup-mongodb-container:
	docker-compose up --build -d mongodb

shutdown-mongodb-container:
	docker-compose down -v mongodb

remove-mongodb-image:
	docker rmi desafio-final-mongodb
